/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthRecipesImport } from './routes/_auth/recipes'
import { Route as AuthRecipesUsernameSlugImport } from './routes/_auth/recipes_/$username.$slug'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRecipesRoute = AuthRecipesImport.update({
  path: '/recipes',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRecipesUsernameSlugRoute = AuthRecipesUsernameSlugImport.update({
  path: '/recipes/$username/$slug',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_auth/recipes': {
      id: '/_auth/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof AuthRecipesImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/recipes/$username/$slug': {
      id: '/_auth/recipes/$username/$slug'
      path: '/recipes/$username/$slug'
      fullPath: '/recipes/$username/$slug'
      preLoaderRoute: typeof AuthRecipesUsernameSlugImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthRoute: AuthRoute.addChildren({
    AuthRecipesRoute,
    AuthIndexRoute,
    AuthRecipesUsernameSlugRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/recipes",
        "/_auth/",
        "/_auth/recipes/$username/$slug"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_auth/recipes": {
      "filePath": "_auth/recipes.tsx",
      "parent": "/_auth"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/recipes/$username/$slug": {
      "filePath": "_auth/recipes_/$username.$slug.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
